services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node
    command: npm run dev
    ports:
      - target: 5173
        host_ip: 127.0.0.1
        published: 5173
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: .
        target: /sample-vite
    tty: true
    stdin_open: true
